### ISSUE TITLE
Setting UPSTREAM_IRONIC=true results in rpc auth failures

### ISSUE THREAD

**Issue by derekhiggins** [openshift-metal3/dev-scripts#1099]
**Describe the bug**
After setting  UPSTREAM_IRONIC=true in dev-scripts the ironic-api fails with the following error

2020-09-09 09:44:28.082 36 ERROR ironic.api.expose [req-bf85baa5-fc99-41ac-8a65-6f28bdf19b14 ironic-user - - - -] Server-side error: "No valid authentication is available". Detail: 
Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/ironic/api/expose.py", line 78, in callfunction
    result = f(self, *args, **kwargs)

  File "/usr/lib/python3.6/site-packages/ironic/api/controllers/v1/node.py", line 2304, in post
    new_node, topic)

  File "/usr/lib/python3.6/site-packages/ironic/conductor/rpcapi.py", line 227, in create_node
    return cctxt.call(context, 'create_node', node_obj=node_obj)

  File "/usr/lib/python3.6/site-packages/ironic/common/json_rpc/client.py", line 123, in call
    **kwargs)

  File "/usr/lib/python3.6/site-packages/ironic/common/json_rpc/client.py", line 174, in _request
    result = _get_session().post(url, json=body)

  File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 401, in post
    return self.request(url, 'POST', **kwargs)

  File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 257, in request
    return self.session.request(url, method, **kwargs)

  File "/usr/lib/python3.6/site-packages/keystoneauth1/session.py", line 784, in request
    raise exceptions.AuthorizationFailure(msg)

keystoneauth1.exceptions.auth.AuthorizationFailure: No valid authentication is available

**Comment by derekhiggins** [comment]
The problem appears to be that we now change DEFAULT.auth_strategy in configure-ironic.sh which also changes json_rpc.auth_strategy (as its not set by our ironic.conf merge)

**Comment by derekhiggins** [comment]
Fixed by https://github.com/metal3-io/ironic-image/pull/201
