### ISSUE TITLE
Ironic-Conductor Container Dies When IPv6 is Disabled on Bootstrap Node

### ISSUE THREAD

**Issue by schmaustech** [openshift-metal3/dev-scripts#663]
**Describe the bug**
When testing with bootstrap node having IPv6 disabled ironic-conductor pod exited out:

2019-07-10 11:46:25.182 1 ERROR oslo.service.wsgi [req-497ebe09-f5d7-48e2-bd27-a6246be566c1 - - - - -] Could not bind to :::8089: error: [Errno 97] Address family not supported by protocol
2019-07-10 11:46:25.182 1 ERROR oslo_service.service [req-497ebe09-f5d7-48e2-bd27-a6246be566c1 - - - - -] Error starting thread.: error: [Errno 97] Address family not supported by protocol
2019-07-10 11:46:25.182 1 ERROR oslo_service.service Traceback (most recent call last):
2019-07-10 11:46:25.182 1 ERROR oslo_service.service   File "/usr/lib/python2.7/site-packages/oslo_service/service.py", line 796, in run_service
2019-07-10 11:46:25.182 1 ERROR oslo_service.service     service.start()
2019-07-10 11:46:25.182 1 ERROR oslo_service.service   File "/usr/lib/python2.7/site-packages/ironic/common/rpc_service.py", line 53, in start
2019-07-10 11:46:25.182 1 ERROR oslo_service.service     serializer)
2019-07-10 11:46:25.182 1 ERROR oslo_service.service   File "/usr/lib/python2.7/site-packages/ironic/common/json_rpc/server.py", line 100, in __init__
2019-07-10 11:46:25.182 1 ERROR oslo_service.service     use_ssl=CONF.json_rpc.use_ssl)
2019-07-10 11:46:25.182 1 ERROR oslo_service.service   File "/usr/lib/python2.7/site-packages/oslo_service/wsgi.py", line 115, in __init__
2019-07-10 11:46:25.182 1 ERROR oslo_service.service     self.socket = self._get_socket(host, port, backlog)
2019-07-10 11:46:25.182 1 ERROR oslo_service.service   File "/usr/lib/python2.7/site-packages/oslo_service/wsgi.py", line 143, in _get_socket
2019-07-10 11:46:25.182 1 ERROR oslo_service.service     sock = eventlet.listen(bind_addr, family, backlog=backlog)
2019-07-10 11:46:25.182 1 ERROR oslo_service.service   File "/usr/lib/python2.7/site-packages/eventlet/convenience.py", line 49, in listen
2019-07-10 11:46:25.182 1 ERROR oslo_service.service     sock = socket.socket(family, socket.SOCK_STREAM)
2019-07-10 11:46:25.182 1 ERROR oslo_service.service   File "/usr/lib/python2.7/site-packages/eventlet/greenio/base.py", line 136, in __init__
2019-07-10 11:46:25.182 1 ERROR oslo_service.service     fd = _original_socket(family, *args, **kwargs)
2019-07-10 11:46:25.182 1 ERROR oslo_service.service   File "/usr/lib64/python2.7/socket.py", line 187, in __init__
2019-07-10 11:46:25.182 1 ERROR oslo_service.service     _sock = _realsocket(family, type, proto)
2019-07-10 11:46:25.182 1 ERROR oslo_service.service error: [Errno 97] Address family not supported by protocol

**To Reproduce**
On a RHEL8 bootstrap node disable IPv6 at kernel/startup

**Expected/observed behavior**
Deployment should succeed even in ipv6 is disabled unless ipv6 is a requirement?

**Additional context**
We need to either document that ipv6 is a requirement and/or document how someone can use the deployment without ipv6.

**Comment by hardys** [comment]
Just to confirm, but bootstrap node, you mean the provisioning host where you run dev-scripts?

That being the case the ulimate fix for this will be https://github.com/openshift-metal3/kni-installer/pull/100 since then the ironic containers will run inside the bootstrap VM started by the installer (and we won't disable ipv6 inside that VM).

**Comment by schmaustech** [comment]
Correct the provisioning host that launches the bootstrap VM and does the deploy of the cluster.
