### ISSUE TITLE
"panic: runtime error: slice bounds out of range" while "oc adm release extract"

### ISSUE THREAD

**Issue by e-minguez** [openshift-metal3/dev-scripts#734]
**Describe the bug**
Just running a `make` with my usual hardware/environment

**To Reproduce**
From dev-scripts  b37f69396 commit, RHEL8 helper node

**Expected/observed behavior**
```
+ oc adm release extract --registry-config installer--q65IkgS0h2/pullsecret --command=openshift-install --to installer--q65IkgS0h2 registry.svc.ci.openshift.org/kni/release:4.2.0-0.ci-2019-07-31-123929-kni.0
panic: runtime error: slice bounds out of range

goroutine 163 [running]:
bufio.(*Reader).fill(0xc000f35c80)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/bufio/bufio.go:89 +0x211
bufio.(*Reader).WriteTo(0xc000f35c80, 0x2dfa380, 0xc000010838, 0x7f60a71fde08, 0xc000f35c80, 0x1)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/bufio/bufio.go:511 +0x106
io.copyBuffer(0x2dfa380, 0xc000010838, 0x2df4f60, 0xc000f35c80, 0x0, 0x0, 0x0, 0xc0013e5260, 0xc0000edb00, 0x0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/io/io.go:384 +0x34e
io.Copy(...)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/io/io.go:364
os/exec.(*Cmd).stdin.func1(0xc000ef4900, 0x0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/os/exec/exec.go:243 +0x67
os/exec.(*Cmd).Start.func1(0xc0008f34a0, 0xc0014f7680)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/os/exec/exec.go:409 +0x27
created by os/exec.(*Cmd).Start
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/os/exec/exec.go:408 +0x58f
make: *** [Makefile:21: ocp_run] Error 2
```

**Additional context**
`make clean` and running `make` again works.

**Comment by karmab** [comment]
i d say it s a network issue with registry.svc.ci.openshift.org

**Comment by hardys** [comment]
Yeah seems like a temporary network outage, maybe raise a bug with that backtrace against the oc repo so that the error can be improved?

Not a dev-scripts bug AFAICS so closing this.

**Comment by russellb** [comment]
@e-minguez even if an outage triggered it, `oc` shouldn't panic like this.  I'd file a bug against openshift/oc
